### PR TITLE
Update names in xacro to match ur_description.

### LINKED ISSUE #2: Updates in ur_description break ur5_demo_support
Due to various renaming conventions and updates in the ur_description package, plan_and_run/demo_setup.launch reports various errors in that it is not able to find several dae/stl and xacro files.

Diff patch follows below:

[patch.zip](https://github.com/ros-industrial-consortium/roscon_2015/files/131064/patch.zip)

### PR DESCRIPTION
**Pull request by jettan**
Fixes #2

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
This looks ok to me (but I'm not the maintainer here). Have you tested these changes in any way?

**Comment by jettan** [comment]
I did and it's now fully working!

**Comment by Jmeyer1292** [comment]
+1 from me.

@shaun-edwards please have a look.

**Comment by davetcoleman** [comment]
+1 I just ran into this problem, pulled this PR, and it fixes the launch file

**Comment by Jmeyer1292** [comment]
ping @shaun-edwards

**Comment by shaun-edwards** [comment]
+1

**Comment by gavanderhoorn** [comment]
Thanks for taking the time to submit a PR, @jettan.

**Pull request merged**
